name: frontend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.2
  intl: ^0.17.0
  dio: ^5.0.1
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

assets: 
  - web/assets/