name: frontend
version: 1.0.0+1
publish_to: none
description: d-network project.
environment:
  sdk: "^3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.5
  intl: ^0.18.0
  dio: ^5.3.0
  get: ^4.6.6
  talker_flutter: ^3.1.9
  data_table_2: ^2.4.3
  # flutter_treeview: ^1.0.7+1
  image_picker: ^1.0.6
  fl_chart: ^0.66.0
  connectivity_plus: ^5.0.2
  universal_html: ^2.2.3
  qr_flutter: ^4.1.0
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  encrypt: ^5.0.0
  crypto: ^3.0.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
 
assets:
  - web/assets/
